title: Happy Life Capital
description: A new private equity International Global Opportunity Fund

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About Us
   url: /about
- title: Global Stregnths
   url: /stregnths
- title: Clear Focus
   url: /focus
- title: Our Team
   url: /team
 - title: Regional Offices
   url: /offices
 - title: Portfolio
   url: /portfolio
 - title: Contact Us
   url: /contact

social:
   email: Jessy_chao@happylifecapital.com
   email: Charles_mao@happylifecapital.com

#google_analytics: ""
