
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

title: "HLC"
description: "A new private equity International Global Opportunity Fund"

url: "www.happylifecapital.com"
baseurl: ""

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   email: Jessy_chao@happylifecapital.com
   email: Charles_mao@happylifecapital.com

#google_analytics: ""